//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoApp.Shared.ResourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ToDoApp.Shared.ResourceFiles.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string btn_Add {
            get {
                return ResourceManager.GetString("btn_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string btn_Cancel {
            get {
                return ResourceManager.GetString("btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string btn_Delete {
            get {
                return ResourceManager.GetString("btn_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string btn_Edit {
            get {
                return ResourceManager.GetString("btn_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string btn_No {
            get {
                return ResourceManager.GetString("btn_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string btn_Save {
            get {
                return ResourceManager.GetString("btn_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string btn_Search {
            get {
                return ResourceManager.GetString("btn_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string btn_Yes {
            get {
                return ResourceManager.GetString("btn_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is required!.
        /// </summary>
        public static string er_ToDoModel_DescriptionRequired {
            get {
                return ResourceManager.GetString("er_ToDoModel_DescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DueDate must be not in the past!.
        /// </summary>
        public static string er_ToDoModel_DueDateInvalid {
            get {
                return ResourceManager.GetString("er_ToDoModel_DueDateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DueDate is required!.
        /// </summary>
        public static string er_ToDoModel_DueDateRequired {
            get {
                return ResourceManager.GetString("er_ToDoModel_DueDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is required!.
        /// </summary>
        public static string er_ToDoModel_TitleRequired {
            get {
                return ResourceManager.GetString("er_ToDoModel_TitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add ToDo.
        /// </summary>
        public static string HeadingAddTodo {
            get {
                return ResourceManager.GetString("HeadingAddTodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit ToDo.
        /// </summary>
        public static string HeadingEditTodo {
            get {
                return ResourceManager.GetString("HeadingEditTodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have chosen to leave the form and you will lose your unsaved data. Select Yes to save your changes and leave, No to cancel your changes and leave..
        /// </summary>
        public static string info_ToDoCancelMessage {
            get {
                return ResourceManager.GetString("info_ToDoCancelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string LangSelectorEnglish {
            get {
                return ResourceManager.GetString("LangSelectorEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LangSelectorLabel {
            get {
                return ResourceManager.GetString("LangSelectorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romanian.
        /// </summary>
        public static string LangSelectorRomanian {
            get {
                return ResourceManager.GetString("LangSelectorRomanian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string lbl_ToDoDescription {
            get {
                return ResourceManager.GetString("lbl_ToDoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Date.
        /// </summary>
        public static string lbl_ToDoDueDate {
            get {
                return ResourceManager.GetString("lbl_ToDoDueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string lbl_ToDoTitle {
            get {
                return ResourceManager.GetString("lbl_ToDoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToDo - Add.
        /// </summary>
        public static string PageTitleAddTodo {
            get {
                return ResourceManager.GetString("PageTitleAddTodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToDo - Edit.
        /// </summary>
        public static string PageTitleEditTodo {
            get {
                return ResourceManager.GetString("PageTitleEditTodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchInputPlaceholder {
            get {
                return ResourceManager.GetString("SearchInputPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string th_ToDoActions {
            get {
                return ResourceManager.GetString("th_ToDoActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string th_ToDoDescription {
            get {
                return ResourceManager.GetString("th_ToDoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Date.
        /// </summary>
        public static string th_ToDoDueDate {
            get {
                return ResourceManager.GetString("th_ToDoDueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string th_ToDoId {
            get {
                return ResourceManager.GetString("th_ToDoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string th_ToDoTitle {
            get {
                return ResourceManager.GetString("th_ToDoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToDos.
        /// </summary>
        public static string ToDoListName {
            get {
                return ResourceManager.GetString("ToDoListName", resourceCulture);
            }
        }
    }
}
